import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import FloatingCartButton from "@/components/FloatingActionButton";
import ScrollToTopButton from "@/components/ScrollToTopButton";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "smn fashion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Nav />
        <StairTransition/>
        <PageTransition>
        {children}
        <FloatingCartButton/>
        <ScrollToTopButton/>
        </PageTransition>
        <Footer />
        {/* The Toaster component is placed here, which will show the toast notifications */}
        <Toaster />
      </body>
    </html>
  );
}
